#!/usr/bin/env python3
# Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
#
# Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
# the people's Republic of China and other countries.
# All Allwinner Technology Co.,Ltd. trademarks are used with permission.
#
# DISCLAIMER
# THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
# IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
# IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
# ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
# ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
# COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
# YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
#
# THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
# PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
# WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
# THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
# OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Author: Jiajian Li <lijiajian@allwinnertech.com>
# Author: Yuanjing Zhang <zhangyuanjing@allwinnertech.com>
#

import os, sys
import argparse

from quickconfig.utils import load_buildconfig, DiffSummary
from quickconfig.parser.tinalinux import TinaLinuxParser

VERSION = "2.0.2"

BANNER = \
"""
 _____     _     _   _____         ___ _
|     |_ _|_|___| |_|     |___ ___|  _|_|___
|  |  | | | |  _| '_|   --| . |   |  _| | . |
|__  _|___|_|___|_,_|_____|___|_|_|_| |_|_  |
   |__|                                 |___|
"""

def print_banner():
    print(BANNER)
    print("=============================================")
    print(f" Quick Config ToolKit: Version {VERSION}")
    print("=============================================")


def check_os_type():
    pass


def args_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument("buildconfig", default="../../.buildconfig", help="the buildconfig file")
    parser.add_argument("-c", "--config", nargs='?', default="", help="configuration items that need to be loaded (optional)")
    parser.add_argument("-f", "--force", action="store_true", help="force exec quick config item, no check, use at your own risk")
    parser.add_argument("-i", "--include", nargs='?', default="", help="include quick_config config file in default/quick_config")
    parser.add_argument("-gd", "--gen_dts_base", action="store_true", help="generate quick_config base with given dts node")
    args = parser.parse_args()

    if not os.path.exists(args.buildconfig):
        print("%s not exists" % args.buildconfig)
        sys.exit(1)
    return args


if __name__ == "__main__":
    args = args_parser()
    # run quick_config
    try:
        config = load_buildconfig(args.buildconfig)
        parser = TinaLinuxParser(args, config, print_banner=print_banner)
    except KeyboardInterrupt:
        print("\n")
        pass
